[package]
name = "teefriends"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serverbrowse = { git = "https://github.com/heinrich5991/libtw2.git" }
